### ISSUE TITLE
Fabric - Advancements

### ISSUE THREAD

**Issue by unilock** [fooooooooooooooo/yep-paper#1]
I made a fork that adds support for advancements via "[Iceberg](https://www.curseforge.com/minecraft/mc-mods/iceberg-fabric)", an external dependency:
https://github.com/unilock/yep-paper/tree/fabric-fix

...But it would probably be best to keep yep standalone, for ease of updating, etc.

Looks like Iceberg uses a mixin ([PlayerAdvancementsMixin](https://github.com/AHilyard/Iceberg/blob/1.19-fabric/src/main/java/com/anthonyhilyard/iceberg/mixin/PlayerAdvancementsMixin.java)) to inject an event ([CriterionCallback](https://github.com/AHilyard/Iceberg/blob/1.19-fabric/src/main/java/com/anthonyhilyard/iceberg/events/CriterionCallback.java)) that's fired whenever an advancement is rewarded. (note that Iceberg uses Mojmaps)
I'd reimplement it myself if I knew enough Java to avoid license violations (from blatant copy/pasting).

What do you think?

**Comment by fooooooooooooooo** [comment]
would using iceberg temporarily until me or someone implements it directly be a good option?

**Comment by unilock** [comment]
As long as it works, I don't see why not 🤷‍♀️

And it *does* work - though I've only tested with just yep + Iceberg + Fabric API installed, so I'm not sure of compatibility with other mods (though I doubt there'll be much conflict, if any at all).

By the way, have you considered publishing VelocityDiscord + yep somewhere like [Modrinth](https://www.modrinth.com/)?

**Comment by fooooooooooooooo** [comment]
just noticed modrinth now has support for velocity plugins, thats sick

before publishing yep i would like to rename it to something better though

**Comment by unilock** [comment]
Fixed with #2.
