### ISSUE TITLE
Wake up, 1.20 is out

### ISSUE THREAD

**Issue by F-fengzi** [fooooooooooooooo/yep-paper#9]

**Comment by fooooooooooooooo** [comment]
currently reinstalling my entire os, I'll try my best

**Comment by unilock** [comment]
I ported yep-fabric to 1.20.1. It's just buildscript and dependency updates, really.
https://github.com/unilock/yep/tree/fabric/1.20.1

I would've made a PR, but I'm not sure whether you'd want to keep a separate `fabric/1.20.1` branch, or just keep the one `fabric` branch? Considering the mod is feature-complete as it is, so there shouldn't be a need to release another 1.19.2 version in the future.

I also ported yep-forge to 1.19.2. Same thing about the necessity for a new branch there. Maybe `forge/1.18.2` should be renamed to `forge/latest`...?
https://github.com/unilock/yep/tree/forge/1.19.2

**Comment by fooooooooooooooo** [comment]
is there any good established convention for supporting multiple versions in mods? ive only seen the one branch per version method but how should you port changes, just make the same commit 6 times?

**Comment by unilock** [comment]
I think multiple branches + a lot of cherry-picking is the best way to go, unfortunately.

An alternative would be a massive Gradle multi-project mono-branch, but that would make cloning + importing + building everything take quite a lot longer than it would otherwise.

**Comment by fooooooooooooooo** [comment]
> I ported yep-fabric to 1.20.1. It's just buildscript and dependency updates, really. [unilock/yep@`fabric`/1.20.1](https://github.com/unilock/yep/tree/fabric/1.20.1?rgh-link-date=2023-06-16T20%3A37%3A38Z)
> 
> I would've made a PR, but I'm not sure whether you'd want to keep a separate `fabric/1.20.1` branch, or just keep the one `fabric` branch? Considering the mod is feature-complete as it is, so there shouldn't be a need to release another 1.19.2 version in the future.
> 
> I also ported yep-forge to 1.19.2. Same thing about the necessity for a new branch there. Maybe `forge/1.18.2` should be renamed to `forge/latest`...? [unilock/yep@`forge`/1.19.2](https://github.com/unilock/yep/tree/forge/1.19.2?rgh-link-date=2023-06-16T20%3A37%3A38Z)

created the branches `fabric/1.20` and `forge/1.19.2`

**Comment by unilock** [comment]
@fooooooooooooooo Could you make a `forge/1.20` branch as well?

On that note - I wonder if it would be better to skip straight to 1.20.1? That seems to be what most mods are targeting at this point - even Fabric's Yarn is focusing on 1.20.1, as is Forge's FML.

**Comment by fooooooooooooooo** [comment]
i think it would be better to leave it at 1.20 until there is definitive a 1.20.x version like there is for 1.19.4, 1.7.10, etc

**Comment by unilock** [comment]
OK, makes sense to me. The mod is probably small enough to not always need the latest mappings / loader updates, anyway.

**Comment by fooooooooooooooo** [comment]
this is done i think
